apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-kafka-consumer
  name: python-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-kafka-consumer
  template:
    metadata:
      labels:
        app: python-kafka-consumer
    spec:
      containers:
        - name: python-kafka-consumer
          image: quay.io/strimzi-examples/python-kafka-consumer:latest
          env:
            - name: STRIMZI_TOPIC
              value: my-topic
            - name: STRIMZI_DELAY_MS
              value: "2000"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
